#!/usr/bin/env python3
"""Generate matched baseline and terrain Nav2 params from the Carter params.

Both files start from the same source so the A/B differs only by the
terrain layer. Run after any change to the source params.

    python3 bringup/make_params.py
"""

import argparse
import copy
import os
import pathlib

import yaml

HERE = pathlib.Path(__file__).resolve().parent
DEFAULT_SRC = os.path.expanduser(
    "~/IsaacSim-ros_workspaces/jazzy_ws/src/navigation/carter_navigation/"
    "params/carter_navigation_params.yaml"
)

LAYER_NAME = "terrain_layer"
LAYER_PARAMS = {
    "plugin": "terrain_costmap::TerrainLayer",
    "enabled": True,
    "cloud_topic": "/front_3d_lidar/lidar_points",
    "robot_base_frame": "base_link",
    "resolution": 0.10,
    "size": 12.0,
    "min_range": 0.7,
    "max_range": 6.0,
    "band_below": 0.5,
    "band_above": 0.35,
    "fusion_alpha": 0.3,
    "max_cell_spread": 0.12,
    "window": 0.5,
    "min_valid_fraction": 0.25,
    "slope_free_deg": 5.0,
    "slope_max_cost_deg": 20.0,
    "slope_lethal_deg": 25.0,
    "roughness_free": 0.005,
    "roughness_max_cost": 0.025,
    "max_cost": 252,
}


def costmap_params(cfg: dict, name: str) -> dict:
    node = cfg[name]
    if name in node:  # nested form: local_costmap: local_costmap: ros__parameters
        node = node[name]
    return node["ros__parameters"]


def add_layer(cfg: dict, costmap: str) -> None:
    p = costmap_params(cfg, costmap)
    plugins = list(p["plugins"])
    if LAYER_NAME in plugins:
        return
    # Before inflation so lethal slope cells get inflated like any obstacle.
    at = plugins.index("inflation_layer") if "inflation_layer" in plugins else len(plugins)
    plugins.insert(at, LAYER_NAME)
    p["plugins"] = plugins
    p[LAYER_NAME] = copy.deepcopy(LAYER_PARAMS)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=DEFAULT_SRC)
    ap.add_argument("--out-dir", default=str(HERE / "params"))
    args = ap.parse_args()

    with open(args.src) as f:
        base = yaml.safe_load(f)

    terrain = copy.deepcopy(base)
    for costmap in ("local_costmap", "global_costmap"):
        add_layer(terrain, costmap)

    os.makedirs(args.out_dir, exist_ok=True)
    for name, cfg in (("nav2_baseline.yaml", base), ("nav2_terrain.yaml", terrain)):
        path = os.path.join(args.out_dir, name)
        with open(path, "w") as f:
            f.write(f"# Generated by bringup/make_params.py from {args.src}\n")
            yaml.safe_dump(cfg, f, sort_keys=False)
        print(f"wrote {path}")

    for costmap in ("local_costmap", "global_costmap"):
        print(f"{costmap} plugins: {costmap_params(terrain, costmap)['plugins']}")


if __name__ == "__main__":
    main()
